### creating User 

POST http://localhost:3000/user/create
content-type: application/json

{
    "email": "lkasfj@lkj.com",
    "password":"adffafvsvx"
}

### find a particular with a user email
GET http://localhost:3000/user/findUser/lkj@lkj.com


### find a particular user with id
GET http://localhost:3000/user/findOne/2


###find all user 
GET http://localhost:3000/user/findAllUser


### Delete a user with the given ID
DELETE  http://localhost:3000/user/remove/2


###Update a user 
PATCH http://localhost:3000/user/update/1
content-type: application/json

{
    "email": "saurabh@asdf.com",
    "password":"saurabh"
}